# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2cc2bcbff4df94a866137dc1e97c03dc5b72089e9092e8bdf894c48c272891119266ad83b8627ca2a1574c9c487520f25cdae335b5997905cd2369f3769275

test:
  secret_key_base: c246da95636eec4cb503d16e910acce48a1466b022967bddabc376f2306875f84f4b7b8f957cff6f3776cd86abece34313a701f7d2e2f39dd2b32b2ee871e1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
